-- Reconstructed PostgreSQL deployment for BDPatient / pndbase.
-- Source of truth: SQL emitted by the C++/Qt application.
-- Intended for a fresh PostgreSQL 12+ database.

BEGIN;

SET client_encoding = 'UTF8';
SET DateStyle = 'ISO, DMY';
SET search_path = public, test, library, messager, reports_library, logs;

CREATE SCHEMA IF NOT EXISTS test;
CREATE SCHEMA IF NOT EXISTS library;
CREATE SCHEMA IF NOT EXISTS messager;
CREATE SCHEMA IF NOT EXISTS reports_library;
CREATE SCHEMA IF NOT EXISTS logs;

-- ---------------------------------------------------------------------------
-- Lookup and library data
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS library.departments (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS library.contact_list (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS library.analizes (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS library.preparate_list (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    international_name  text NOT NULL UNIQUE,
    description         text NOT NULL DEFAULT '',
    dose                text NOT NULL DEFAULT '',
    delete_row          boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS test.area (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS test.street (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text NOT NULL UNIQUE,
    staff_add_id    bigint,
    time_stamp      timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS test.why_removed (
    id          integer PRIMARY KEY,
    description text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS test.direct (
    id          integer PRIMARY KEY,
    description text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS test.direct_from (
    id          integer PRIMARY KEY,
    description text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS test."end" (
    id          integer PRIMARY KEY,
    description text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS test.document (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_end      integer NOT NULL REFERENCES test."end"(id),
    description text NOT NULL,
    UNIQUE (id_end, description)
);

CREATE TABLE IF NOT EXISTS test.type_work_place (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS test.who_closed (
    id          integer PRIMARY KEY,
    who         text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS test.tsuicide (
    id          integer PRIMARY KEY,
    description text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS test.group_diagnos (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                text NOT NULL UNIQUE,
    array_diagnos_id    bigint[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS reports_library.analize_vyt_group_diagnos (
    id              bigint PRIMARY KEY,
    name            text NOT NULL DEFAULT '',
    group_diagnos   bigint[] NOT NULL DEFAULT '{}'
);

-- ---------------------------------------------------------------------------
-- Users, staff, access and operational logging
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS test.staff (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname               text NOT NULL DEFAULT '',
    name                text NOT NULL DEFAULT '',
    mname               text NOT NULL DEFAULT '',
    position            integer NOT NULL DEFAULT 0,
    code                text NOT NULL DEFAULT '',
    status              integer NOT NULL DEFAULT 0,
    support_department  text NOT NULL DEFAULT '1'
);

ALTER TABLE test.street
    DROP CONSTRAINT IF EXISTS street_staff_add_id_fkey;
ALTER TABLE test.street
    ADD CONSTRAINT street_staff_add_id_fkey
    FOREIGN KEY (staff_add_id) REFERENCES test.staff(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS test.users (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id            bigint NOT NULL UNIQUE REFERENCES test.staff(id),
    user_login          text NOT NULL UNIQUE,
    password_login_md5  char(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS test.rights (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint NOT NULL UNIQUE REFERENCES test.users(id) ON DELETE CASCADE,
    rights      text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS test.servising_area (
    staff_id    bigint NOT NULL REFERENCES test.staff(id) ON DELETE CASCADE,
    area_id     bigint NOT NULL REFERENCES test.area(id) ON DELETE CASCADE,
    PRIMARY KEY (staff_id, area_id)
);

CREATE TABLE IF NOT EXISTS test.logs (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_add_id    bigint REFERENCES test.staff(id) ON DELETE SET NULL,
    date_add        date NOT NULL DEFAULT current_date,
    text            text NOT NULL,
    time_stamp      timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS logs.error (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text        text NOT NULL,
    created_at  timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS test.session (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- QHostAddress::toString() may include an IPv6 scope identifier, so keep text.
    ip_adres            text NOT NULL DEFAULT '',
    date_time_start     timestamp without time zone NOT NULL DEFAULT clock_timestamp(),
    date_time_stop      timestamp without time zone,
    staff               bigint NOT NULL REFERENCES test.staff(id),
    state               integer NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS session_staff_state_idx ON test.session (staff, state);

CREATE TABLE IF NOT EXISTS test.tasks (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text_task   text NOT NULL,
    status      integer NOT NULL DEFAULT 0,
    session_id  bigint REFERENCES test.session(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- Patient core
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS test.patient (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname               text NOT NULL,
    name                text NOT NULL,
    mname               text NOT NULL DEFAULT '',
    serial_passport     text NOT NULL DEFAULT '',
    number_passport     text NOT NULL DEFAULT '',
    status              integer NOT NULL DEFAULT 99,
    staff_add_id        bigint REFERENCES test.staff(id),
    vidan               text NOT NULL DEFAULT '',
    delete_row          boolean NOT NULL DEFAULT false,
    time_stamp          timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX IF NOT EXISTS patient_name_idx ON test.patient (fname, name, mname);
CREATE INDEX IF NOT EXISTS patient_status_idx ON test.patient (status) WHERE NOT delete_row;

CREATE TABLE IF NOT EXISTS test.medcard (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id              bigint NOT NULL UNIQUE REFERENCES test.patient(id) ON DELETE CASCADE,
    sex                     boolean NOT NULL DEFAULT false,
    birthday                date,
    job_place               text NOT NULL DEFAULT '',
    tutor                   boolean NOT NULL DEFAULT false,
    pt                      boolean NOT NULL DEFAULT false,
    group_lgot_preparat     text NOT NULL DEFAULT '',
    area_id                 bigint NOT NULL REFERENCES test.area(id),
    serial_snils            text NOT NULL DEFAULT '',
    district_id             integer NOT NULL DEFAULT 1,
    group_inv_obsh          text NOT NULL DEFAULT '',
    polis_serial            text NOT NULL DEFAULT '',
    polis_number            text NOT NULL DEFAULT '',
    department              bigint NOT NULL REFERENCES library.departments(id),
    time_stamp              timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX IF NOT EXISTS medcard_area_idx ON test.medcard (area_id);
CREATE INDEX IF NOT EXISTS medcard_department_idx ON test.medcard (department);
CREATE INDEX IF NOT EXISTS medcard_birthday_idx ON test.medcard (birthday);

CREATE TABLE IF NOT EXISTS test.address_patient (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medcard_id  bigint NOT NULL UNIQUE REFERENCES test.medcard(id) ON DELETE CASCADE,
    street_id   bigint NOT NULL REFERENCES test.street(id),
    building    text NOT NULL DEFAULT '',
    home        text NOT NULL DEFAULT '',
    flat        text NOT NULL DEFAULT '',
    telefon     text NOT NULL DEFAULT '',
    index_adrr  text NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS address_patient_street_idx ON test.address_patient (street_id);

-- Column order is significant for QSqlRelationalTableModel in dialog_patient.cpp.
CREATE TABLE IF NOT EXISTS test.uchet (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medcard_id      bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    on_uchet        date,
    off_uchet       date,
    why_removed_id  integer NOT NULL DEFAULT -1 REFERENCES test.why_removed(id),
    staff_add_id    bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    direct          integer NOT NULL DEFAULT -1 REFERENCES test.direct(id),
    direct_from     integer NOT NULL DEFAULT -1 REFERENCES test.direct_from(id),
    delete_row      boolean NOT NULL DEFAULT false,
    time_stamp      timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX IF NOT EXISTS uchet_medcard_active_idx ON test.uchet (medcard_id, id DESC) WHERE NOT delete_row;

CREATE TABLE IF NOT EXISTS test.comments (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        integer NOT NULL DEFAULT 0,
    staff       bigint NOT NULL REFERENCES test.staff(id),
    comment     text NOT NULL,
    medcard_id  bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    delete_row  boolean NOT NULL DEFAULT false,
    time_stamp  timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

-- Column order is used directly by QSqlTableModel and QSqlQuery::value().
CREATE TABLE IF NOT EXISTS test.text_info_patients (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medcard_id      bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    type            integer NOT NULL DEFAULT 0,
    date_creat      date NOT NULL DEFAULT current_date,
    staff_add_id    bigint NOT NULL REFERENCES test.staff(id),
    text            text NOT NULL DEFAULT '',
    delete_row      boolean NOT NULL DEFAULT false,
    doc_id          bigint NOT NULL REFERENCES test.document(id),
    time_stamp      timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

-- ---------------------------------------------------------------------------
-- Diagnoses, observation, visits and hospitalization
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS test.diagnos (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text NOT NULL,
    code            text NOT NULL UNIQUE,
    staff_add_id    bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id)
);

CREATE TABLE IF NOT EXISTS test.diagnos_patient (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medcard_id              bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    diagnos_id              bigint NOT NULL REFERENCES test.diagnos(id),
    staff_add_id            bigint NOT NULL REFERENCES test.staff(id),
    fixing_diagnos_date     date NOT NULL DEFAULT current_date,
    id_parent               bigint REFERENCES test.diagnos_patient(id) ON DELETE CASCADE,
    delete_row              boolean NOT NULL DEFAULT false,
    first                   boolean NOT NULL DEFAULT false,
    time_stamp              timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX IF NOT EXISTS diagnos_patient_medcard_idx
    ON test.diagnos_patient (medcard_id, id DESC);
CREATE INDEX IF NOT EXISTS diagnos_patient_active_main_idx
    ON test.diagnos_patient (medcard_id, fixing_diagnos_date DESC)
    WHERE NOT delete_row AND id_parent IS NULL;

CREATE TABLE IF NOT EXISTS test.dynamic_view (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medcard_id          bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    on_date             date NOT NULL,
    delete_row          boolean NOT NULL DEFAULT false,
    staff_add_id        bigint NOT NULL REFERENCES test.staff(id),
    group_disp_view     text NOT NULL,
    status              boolean NOT NULL DEFAULT false,
    diagnos_id          bigint REFERENCES test.diagnos_patient(id),
    stop_date           date,
    cause               text NOT NULL DEFAULT '',
    staff_del_id        bigint REFERENCES test.staff(id),
    time_stamp          timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX IF NOT EXISTS dynamic_view_medcard_idx ON test.dynamic_view (medcard_id);
CREATE INDEX IF NOT EXISTS dynamic_view_open_idx
    ON test.dynamic_view (group_disp_view, medcard_id) WHERE NOT delete_row AND NOT status;

CREATE TABLE IF NOT EXISTS test.visits_control (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_assigned   date NOT NULL,
    medcard_id      bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    staff_add_id    bigint NOT NULL REFERENCES test.staff(id),
    delete_row      boolean NOT NULL DEFAULT false,
    date_presence   date,
    cause           text NOT NULL DEFAULT '',
    time_stamp      timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX IF NOT EXISTS visits_control_medcard_idx ON test.visits_control (medcard_id);
CREATE INDEX IF NOT EXISTS visits_control_date_idx ON test.visits_control (date_assigned) WHERE NOT delete_row;

CREATE TABLE IF NOT EXISTS test.hospitalization (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medcard_id      bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    staff_add_id    bigint NOT NULL REFERENCES test.staff(id),
    who_wrote       integer NOT NULL DEFAULT 0,
    date_up         date NOT NULL,
    date_down       date,
    delete_row      boolean NOT NULL DEFAULT false,
    diagnose_id     bigint REFERENCES test.diagnos_patient(id),
    doctor          bigint REFERENCES test.staff(id),
    first           boolean NOT NULL DEFAULT false,
    time_stamp      timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS test.notwork_list (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_start      date NOT NULL,
    date_stop       date,
    medcard_id      bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    count_day       integer,
    staff_add_id    bigint NOT NULL REFERENCES test.staff(id),
    staff_edit_id   bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    delete_row      boolean NOT NULL DEFAULT false,
    diagnos_id      bigint NOT NULL REFERENCES test.diagnos(id),
    who_open        integer NOT NULL REFERENCES test.who_closed(id),
    who_close       integer REFERENCES test.who_closed(id),
    state           boolean NOT NULL DEFAULT false,
    doctor_open     bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    doctor_close    bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    staff_del_id    bigint REFERENCES test.staff(id),
    time_stamp      timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

-- ---------------------------------------------------------------------------
-- Other patient modules
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS test.invalid_patient (
    id                                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medcard_id                              bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    staff_add_id                            bigint NOT NULL REFERENCES test.staff(id),
    group_inv                               text NOT NULL DEFAULT '-1',
    priznan_trudosp                         boolean NOT NULL DEFAULT false,
    from_other                              boolean NOT NULL DEFAULT false,
    date_peresmotra                         date NOT NULL,
    srok_ocherednogo_pereosvidet            date,
    bs                                      boolean NOT NULL DEFAULT false,
    inv_child                               boolean NOT NULL DEFAULT false,
    delete_row                              boolean NOT NULL DEFAULT false,
    diagnos_id                              bigint REFERENCES test.diagnos_patient(id),
    first                                   boolean NOT NULL DEFAULT false,
    place_work_id                           bigint REFERENCES test.type_work_place(id),
    stepen_utrachenoy_trudosposobnosti      text NOT NULL DEFAULT '',
    dubl                                    boolean NOT NULL DEFAULT false,
    other_recomendation                     text NOT NULL DEFAULT '',
    staff_edit_id                           bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    staff_del_id                            bigint REFERENCES test.staff(id),
    time_stamp                              timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX IF NOT EXISTS invalid_patient_medcard_idx ON test.invalid_patient (medcard_id);

-- Column order is used by QSqlTableModel in mainwindow.cpp.
CREATE TABLE IF NOT EXISTS test.suicide (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datestart       date NOT NULL,
    tsuicide_id     integer NOT NULL REFERENCES test.tsuicide(id),
    staff_add_id    bigint NOT NULL REFERENCES test.staff(id),
    staff_edit_id   bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    medcard_id      bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    delete_row      boolean NOT NULL DEFAULT false,
    time_stamp      timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

-- Column order is used by QSqlTableModel in mainwindow.cpp.
CREATE TABLE IF NOT EXISTS test.ood (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medcard_id          bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    date_ood            date NOT NULL,
    criminal_article   text NOT NULL DEFAULT '',
    staff_add_id        bigint NOT NULL REFERENCES test.staff(id),
    staff_edit_id       bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    delete_row          boolean NOT NULL DEFAULT false,
    time_stamp          timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS test.day_stationar (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medcard_id      bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    staff_add_id    bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    staff_edit_id   bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    delete_row      boolean NOT NULL DEFAULT false,
    day_in          date NOT NULL,
    day_out         date,
    this_close      boolean NOT NULL DEFAULT false,
    time_stamp      timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS test.preparate (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_add_id                bigint NOT NULL REFERENCES test.staff(id),
    staff_edit_id               bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    deleted_row                 boolean NOT NULL DEFAULT false,
    medcard_id                  bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    date_first_appointment      date NOT NULL,
    date_vk                     date,
    preparate_id                bigint NOT NULL REFERENCES library.preparate_list(id),
    time_stamp                  timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS test.data_analizes (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medcard_id          bigint NOT NULL REFERENCES test.medcard(id) ON DELETE CASCADE,
    staff_add_id        bigint NOT NULL REFERENCES test.staff(id),
    staff_edit_id       bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    staff_del_id        bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    delete_row          boolean NOT NULL DEFAULT false,
    date_appointment    date NOT NULL,
    type_analizes       bigint NOT NULL REFERENCES library.analizes(id),
    time_stamp          timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

-- ---------------------------------------------------------------------------
-- Journals
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS test.journal_rvk (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_creat_record       date NOT NULL DEFAULT current_date,
    doctor                  bigint REFERENCES test.staff(id),
    medcard_id              bigint REFERENCES test.medcard(id) ON DELETE SET NULL,
    street_id               bigint REFERENCES test.street(id),
    house                   text NOT NULL DEFAULT '',
    building                text NOT NULL DEFAULT '',
    flat                    text NOT NULL DEFAULT '',
    diagnos_id              bigint REFERENCES test.diagnos(id),
    result                  text NOT NULL DEFAULT '',
    who_signed_predsed      bigint REFERENCES test.staff(id),
    who_signed_zav_otdel    bigint REFERENCES test.staff(id),
    who_signed_doctor       bigint REFERENCES test.staff(id),
    when_signed             date,
    name_responsible        text NOT NULL DEFAULT '',
    staff_add_id            bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    staff_edit_id           bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    delete_row              boolean NOT NULL DEFAULT false,
    time_stamp              timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS test.journal_zapros (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    in_date_doc         date,
    in_number_doc       bigint,
    who_send            bigint REFERENCES library.contact_list(id),
    fname_p             text NOT NULL DEFAULT '',
    name_p              text NOT NULL DEFAULT '',
    oname_p             text NOT NULL DEFAULT '',
    birthday_p          date,
    street_id           bigint REFERENCES test.street(id),
    building_p          bigint,
    house_p             bigint,
    flat_p              bigint,
    area_id             bigint REFERENCES test.area(id),
    diagnos_id          bigint REFERENCES test.diagnos(id),
    doctor_id           bigint REFERENCES test.staff(id),
    -- This is the fixed 1..4 signer enum populated by the dialog, not contact_list.
    who_signed          integer,
    date_signed         date,
    out_date_doc        date,
    out_number_doc      bigint,
    staff_id_respons    bigint NOT NULL DEFAULT 0 REFERENCES test.staff(id),
    delete_row          boolean NOT NULL DEFAULT false,
    time_stamp          timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

-- ---------------------------------------------------------------------------
-- Messenger
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS messager."group" (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE,
    -- dialog_chat.cpp filters groups with "<staff-id> = ANY(staff_id)".
    staff_id    bigint[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS messager.messages (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_from  bigint NOT NULL REFERENCES test.staff(id),
    staff_to    bigint NOT NULL REFERENCES test.staff(id),
    message     text NOT NULL,
    date_add    timestamp without time zone NOT NULL DEFAULT clock_timestamp(),
    read_at     timestamp without time zone
);

CREATE TABLE IF NOT EXISTS messager.group_messages (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        bigint NOT NULL REFERENCES messager."group"(id) ON DELETE CASCADE,
    staff_add_id    bigint NOT NULL REFERENCES test.staff(id),
    message         text NOT NULL,
    date_add        timestamp without time zone NOT NULL DEFAULT clock_timestamp()
);

-- ---------------------------------------------------------------------------
-- Stored function used to create a complete patient record
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.insert_all_info(
    p_fname text,
    p_name text,
    p_mname text,
    p_serial_passport text,
    p_number_passport text,
    p_patient_status integer,
    p_staff_add_id bigint,
    p_vidan text,
    p_patient_delete_row boolean,
    p_sex boolean,
    p_birthday date,
    p_job_place text,
    p_tutor boolean,
    p_pt boolean,
    p_group_lgot_preparat text,
    p_area_id bigint,
    p_district_id integer,
    p_group_inv_obsh text,
    p_polis_serial text,
    p_polis_number text,
    p_serial_snils text,
    p_street_id bigint,
    p_home text,
    p_building text,
    p_flat text,
    p_telefon text,
    p_index_adrr text,
    p_date_add date,
    p_on_uchet date,
    p_off_uchet date,
    p_why_removed_id integer,
    p_direct integer,
    p_direct_from integer,
    p_department bigint
)
RETURNS bigint
LANGUAGE plpgsql
AS $function$
DECLARE
    v_patient_id bigint;
    v_medcard_id bigint;
BEGIN
    INSERT INTO test.patient (
        fname, name, mname, serial_passport, number_passport,
        status, staff_add_id, vidan, delete_row
    ) VALUES (
        p_fname, p_name, COALESCE(p_mname, ''),
        COALESCE(p_serial_passport, ''), COALESCE(p_number_passport, ''),
        p_patient_status, p_staff_add_id, COALESCE(p_vidan, ''),
        COALESCE(p_patient_delete_row, false)
    )
    RETURNING id INTO v_patient_id;

    INSERT INTO test.medcard (
        patient_id, sex, birthday, job_place, tutor, pt,
        group_lgot_preparat, area_id, serial_snils, district_id,
        group_inv_obsh, polis_serial, polis_number, department, time_stamp
    ) VALUES (
        v_patient_id, p_sex, p_birthday, COALESCE(p_job_place, ''),
        p_tutor, p_pt, COALESCE(p_group_lgot_preparat, ''), p_area_id,
        COALESCE(p_serial_snils, ''), p_district_id,
        COALESCE(p_group_inv_obsh, ''), COALESCE(p_polis_serial, ''),
        COALESCE(p_polis_number, ''), p_department,
        COALESCE(p_date_add::timestamp, clock_timestamp())
    )
    RETURNING id INTO v_medcard_id;

    INSERT INTO test.address_patient (
        medcard_id, street_id, home, building, flat, telefon, index_adrr
    ) VALUES (
        v_medcard_id, p_street_id, COALESCE(p_home, ''),
        COALESCE(p_building, ''), COALESCE(p_flat, ''),
        COALESCE(p_telefon, ''), COALESCE(p_index_adrr, '')
    );

    INSERT INTO test.uchet (
        medcard_id, on_uchet, off_uchet, why_removed_id,
        staff_add_id, direct, direct_from, delete_row
    ) VALUES (
        v_medcard_id, p_on_uchet, p_off_uchet, p_why_removed_id,
        p_staff_add_id, p_direct, p_direct_from, false
    );

    INSERT INTO test.logs (staff_add_id, date_add, text)
    VALUES (p_staff_add_id, COALESCE(p_date_add, current_date),
            'Добавлена медкарта № ' || v_medcard_id);

    RETURN v_medcard_id;
END;
$function$;

-- ---------------------------------------------------------------------------
-- Views consumed by QSqlTableModel. Column order is intentionally explicit.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW test.age_patients AS
SELECT
    m.id,
    CASE
        WHEN m.birthday IS NULL THEN NULL::integer
        ELSE date_part('year', age(current_date, m.birthday))::integer
    END AS date_part
FROM test.medcard AS m;

CREATE OR REPLACE VIEW test.all_view_patient AS
SELECT
    m.id,
    p.fname,
    p.name,
    p.mname,
    m.birthday,
    m.sex,
    m.area_id,
    m.district_id,
    m.pt,
    p.status,
    p.delete_row,
    m.department
FROM test.medcard AS m
JOIN test.patient AS p ON p.id = m.patient_id;

CREATE OR REPLACE VIEW public.patients_find AS
SELECT
    m.id,
    p.id AS patient_id,
    concat_ws(' ', p.fname, p.name, p.mname) AS concat,
    p.serial_passport,
    p.number_passport,
    m.birthday,
    p.status,
    m.area_id,
    s.name AS street,
    a.home,
    a.building,
    a.flat,
    a.telefon,
    m.department
FROM test.medcard AS m
JOIN test.patient AS p ON p.id = m.patient_id
LEFT JOIN test.address_patient AS a ON a.medcard_id = m.id
LEFT JOIN test.street AS s ON s.id = a.street_id;

CREATE OR REPLACE VIEW test.main_find_filter AS
SELECT
    m.id AS medcard_id,
    p.fname,
    p.name,
    p.mname,
    m.sex,
    m.birthday,
    m.pt,
    m.area_id,
    m.district_id,
    s.name AS street_name,
    a.home,
    a.building,
    a.flat,
    a.telefon,
    a.index_adrr,
    p.serial_passport,
    p.number_passport,
    p.vidan,
    m.polis_number,
    p.status,
    a.street_id
FROM test.medcard AS m
JOIN test.patient AS p ON p.id = m.patient_id
LEFT JOIN test.address_patient AS a ON a.medcard_id = m.id
LEFT JOIN test.street AS s ON s.id = a.street_id;

CREATE OR REPLACE VIEW test.dynamic_view_patient AS
SELECT
    d.id,
    d.medcard_id,
    d.on_date,
    d.group_disp_view,
    d.status,
    concat_ws(' ', st.fname, st.name, st.mname) AS staff_name,
    d.stop_date,
    d.delete_row
FROM test.dynamic_view AS d
LEFT JOIN test.staff AS st ON st.id = d.staff_add_id;

CREATE OR REPLACE VIEW test.dynamic_view_preview AS
SELECT
    d.id,
    d.medcard_id,
    d.status,
    d.delete_row,
    p.status AS patient_status,
    p.fname,
    p.name,
    p.mname,
    m.sex,
    m.birthday,
    d.group_disp_view,
    m.area_id,
    m.district_id,
    d.on_date,
    d.stop_date,
    m.pt,
    min(d.on_date) OVER (PARTITION BY d.medcard_id) AS first_on_date
FROM test.dynamic_view AS d
JOIN test.medcard AS m ON m.id = d.medcard_id
JOIN test.patient AS p ON p.id = m.patient_id;

CREATE OR REPLACE VIEW test.max_and_min_dynamic AS
SELECT medcard_id, min(on_date) AS min, max(on_date) AS max
FROM test.dynamic_view
WHERE NOT delete_row
GROUP BY medcard_id;

CREATE OR REPLACE VIEW test.visits_control_patient AS
SELECT
    v.id,
    v.medcard_id,
    v.date_assigned,
    concat_ws(' ', st.fname, st.name, st.mname) AS staff_name,
    v.date_presence
FROM test.visits_control AS v
LEFT JOIN test.staff AS st ON st.id = v.staff_add_id
WHERE NOT v.delete_row;

CREATE OR REPLACE VIEW test.visiting_big_table AS
SELECT
    v.id,
    v.medcard_id,
    p.fname,
    p.name,
    p.mname,
    m.area_id,
    COALESCE(d.group_disp_view, '0') AS group_disp_view,
    v.date_assigned,
    concat_ws(' ', st.fname, st.name, st.mname) AS staff_name,
    v.date_presence
FROM test.visits_control AS v
JOIN test.medcard AS m ON m.id = v.medcard_id
JOIN test.patient AS p ON p.id = m.patient_id
LEFT JOIN test.staff AS st ON st.id = v.staff_add_id
LEFT JOIN LATERAL (
    SELECT dv.group_disp_view
    FROM test.dynamic_view AS dv
    WHERE dv.medcard_id = v.medcard_id AND NOT dv.delete_row
    ORDER BY dv.on_date DESC, dv.id DESC
    LIMIT 1
) AS d ON true
WHERE NOT v.delete_row;

CREATE OR REPLACE VIEW test.sved_gosp_patient AS
SELECT
    h.id,
    h.medcard_id,
    h.who_wrote,
    h.date_up,
    h.date_down,
    concat_ws(' ', st.fname, st.name, st.mname) AS staff_name
FROM test.hospitalization AS h
LEFT JOIN test.staff AS st ON st.id = h.staff_add_id
WHERE NOT h.delete_row;

CREATE OR REPLACE VIEW test.not_work_list_view AS
SELECT
    n.id,
    n.medcard_id,
    n.date_start,
    n.date_stop,
    n.count_day,
    d.code AS diagnos,
    concat_ws(' ', sa.fname, sa.name, sa.mname) AS staff_add,
    concat_ws(' ', se.fname, se.name, se.mname) AS staff_edit,
    n.delete_row,
    n.who_open,
    n.who_close
FROM test.notwork_list AS n
LEFT JOIN test.diagnos AS d ON d.id = n.diagnos_id
LEFT JOIN test.staff AS sa ON sa.id = n.staff_add_id
LEFT JOIN test.staff AS se ON se.id = n.staff_edit_id;

CREATE OR REPLACE VIEW test.diagnos_patient_info AS
SELECT
    dp.id,
    dp.diagnos_id,
    d.name,
    dp.medcard_id,
    dp.fixing_diagnos_date,
    dp.first,
    d.code,
    dp.delete_row,
    dp.id_parent
FROM test.diagnos_patient AS dp
JOIN test.diagnos AS d ON d.id = dp.diagnos_id;

CREATE OR REPLACE VIEW test.diagnos_filter AS
SELECT
    dp.medcard_id,
    dp.id AS diagnos_patient_id,
    dp.diagnos_id,
    dp.delete_row,
    p.fname,
    p.name,
    p.mname,
    m.sex,
    m.birthday,
    m.area_id,
    m.district_id,
    dp.fixing_diagnos_date,
    -- Required by Dialog_find_filters::find_filter_diagnos().
    p.status
FROM test.diagnos_patient AS dp
JOIN test.medcard AS m ON m.id = dp.medcard_id
JOIN test.patient AS p ON p.id = m.patient_id;

CREATE OR REPLACE VIEW test.invalid_filter AS
SELECT
    i.medcard_id,
    p.fname,
    p.name,
    p.mname,
    i.group_inv,
    m.area_id,
    i.date_peresmotra,
    i.srok_ocherednogo_pereosvidet,
    p.status,
    tw.description AS place_work,
    i.first,
    i.stepen_utrachenoy_trudosposobnosti,
    concat_ws(' ', se.fname, se.name, se.mname) AS staff_edit,
    i.other_recomendation,
    i.dubl,
    d.code AS diagnos,
    i.inv_child,
    i.bs,
    i.from_other,
    i.priznan_trudosp
FROM test.invalid_patient AS i
JOIN test.medcard AS m ON m.id = i.medcard_id
JOIN test.patient AS p ON p.id = m.patient_id
LEFT JOIN test.type_work_place AS tw ON tw.id = i.place_work_id
LEFT JOIN test.staff AS se ON se.id = i.staff_edit_id
LEFT JOIN test.diagnos_patient AS dp ON dp.id = i.diagnos_id
LEFT JOIN test.diagnos AS d ON d.id = dp.diagnos_id
WHERE NOT i.delete_row;

CREATE OR REPLACE VIEW test.day_stationar_view AS
SELECT
    ds.id,
    ds.medcard_id,
    concat_ws(' ', sa.fname, sa.name, sa.mname) AS staff_add,
    concat_ws(' ', se.fname, se.name, se.mname) AS staff_edit,
    ds.delete_row,
    ds.day_in,
    ds.day_out,
    ds.this_close
FROM test.day_stationar AS ds
LEFT JOIN test.staff AS sa ON sa.id = ds.staff_add_id
LEFT JOIN test.staff AS se ON se.id = ds.staff_edit_id;

CREATE OR REPLACE VIEW test.preparate_view AS
SELECT
    pr.id,
    concat_ws(' ', sa.fname, sa.name, sa.mname) AS staff_add,
    concat_ws(' ', se.fname, se.name, se.mname) AS staff_edit,
    pr.deleted_row,
    pr.medcard_id,
    pl.description,
    pl.dose,
    pr.date_first_appointment,
    pr.date_vk,
    pl.international_name AS preparate
FROM test.preparate AS pr
JOIN library.preparate_list AS pl ON pl.id = pr.preparate_id
LEFT JOIN test.staff AS sa ON sa.id = pr.staff_add_id
LEFT JOIN test.staff AS se ON se.id = pr.staff_edit_id;

CREATE OR REPLACE VIEW test.data_analizes_view AS
SELECT
    da.id,
    da.medcard_id,
    concat_ws(' ', sa.fname, sa.name, sa.mname) AS staff_add,
    concat_ws(' ', se.fname, se.name, se.mname) AS staff_edit,
    concat_ws(' ', sd.fname, sd.name, sd.mname) AS staff_del,
    da.delete_row,
    da.date_appointment,
    a.name AS type_analizes
FROM test.data_analizes AS da
JOIN library.analizes AS a ON a.id = da.type_analizes
LEFT JOIN test.staff AS sa ON sa.id = da.staff_add_id
LEFT JOIN test.staff AS se ON se.id = da.staff_edit_id
LEFT JOIN test.staff AS sd ON sd.id = da.staff_del_id;

CREATE OR REPLACE VIEW test.comments_view AS
SELECT
    c.id,
    c.type,
    c.staff,
    concat_ws(' ', s.fname, s.name, s.mname) AS staff_name,
    c.medcard_id,
    c.comment,
    c.delete_row,
    c.time_stamp,
    s.code AS staff_code
FROM test.comments AS c
LEFT JOIN test.staff AS s ON s.id = c.staff;

CREATE OR REPLACE VIEW test.staff_view AS
SELECT
    id,
    -- QSqlRelation declarations request this exact display-column name.
    concat_ws(' ', fname, name, mname) AS staff_name,
    position,
    code,
    status
FROM test.staff
WHERE status = 0;

CREATE OR REPLACE VIEW test.journal_zapros_view AS
SELECT
    j.id,
    j.in_date_doc,
    j.in_number_doc,
    sender.name AS who_send,
    j.fname_p,
    j.name_p,
    j.oname_p,
    j.birthday_p,
    s.name AS street,
    j.building_p,
    j.house_p,
    j.flat_p,
    a.name AS area,
    d.code AS diagnos,
    concat_ws(' ', doctor.fname, doctor.name, doctor.mname) AS doctor,
    -- model_journal_zapros.cpp converts this numeric enum at column 15.
    j.who_signed,
    j.date_signed,
    j.out_date_doc,
    j.out_number_doc,
    j.delete_row
FROM test.journal_zapros AS j
LEFT JOIN library.contact_list AS sender ON sender.id = j.who_send
LEFT JOIN test.street AS s ON s.id = j.street_id
LEFT JOIN test.area AS a ON a.id = j.area_id
LEFT JOIN test.diagnos AS d ON d.id = j.diagnos_id
LEFT JOIN test.staff AS doctor ON doctor.id = j.doctor_id;

CREATE OR REPLACE VIEW messager.messages_view AS
SELECT
    m.id,
    m.staff_from,
    m.staff_to,
    m.date_add,
    m.message
FROM messager.messages AS m;

CREATE OR REPLACE VIEW messager.messages_groups AS
SELECT
    gm.id,
    gm.group_id,
    gm.staff_add_id,
    gm.date_add,
    gm.message
FROM messager.group_messages AS gm;

CREATE OR REPLACE VIEW reports_library.military AS
SELECT
    m.id AS medcard_id,
    concat_ws(' ', p.fname, p.name, p.mname) AS fio,
    dv.group_disp_view,
    concat_ws(', ', s.name, a.home, a.building, a.flat) AS address,
    m.district_id,
    m.birthday,
    d.code AS diagnos
FROM test.medcard AS m
JOIN test.patient AS p ON p.id = m.patient_id
LEFT JOIN test.address_patient AS a ON a.medcard_id = m.id
LEFT JOIN test.street AS s ON s.id = a.street_id
LEFT JOIN LATERAL (
    SELECT group_disp_view
    FROM test.dynamic_view
    WHERE medcard_id = m.id AND NOT delete_row AND NOT status
    ORDER BY on_date DESC, id DESC
    LIMIT 1
) AS dv ON true
LEFT JOIN LATERAL (
    SELECT dx.code
    FROM test.diagnos_patient AS dp
    JOIN test.diagnos AS dx ON dx.id = dp.diagnos_id
    WHERE dp.medcard_id = m.id AND NOT dp.delete_row AND dp.id_parent IS NULL
    ORDER BY dp.fixing_diagnos_date DESC, dp.id DESC
    LIMIT 1
) AS d ON true
WHERE m.sex
  AND date_part('year', age(current_date, m.birthday)) BETWEEN 18 AND 27
  AND NOT p.delete_row;

-- ---------------------------------------------------------------------------
-- Minimal bootstrap data
-- ---------------------------------------------------------------------------

INSERT INTO library.departments (id, name) VALUES
    (1, 'Основное отделение')
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.area (id, name) VALUES
    (1, 'Участок 1')
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.staff (id, fname, name, mname, position, code, status, support_department) VALUES
    (0, 'Системный', 'пользователь', '', 0, 'SYSTEM', 0, '1'),
    (1, 'Администратор', 'системы', '', 1, 'ADMIN', 0, '1')
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.street (id, name, staff_add_id) VALUES
    (1, 'Не указана', 0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.users (id, staff_id, user_login, password_login_md5) VALUES
    (1, 1, 'admin', '21232f297a57a5a743894a0e4a801fc3')
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.rights (id, user_id, rights) VALUES
    (1, 1, repeat('1', 64))
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.servising_area (staff_id, area_id) VALUES
    (1, 1)
ON CONFLICT DO NOTHING;

INSERT INTO test.why_removed (id, description) VALUES
    (-1, 'Не указано'),
    (0, 'Смерть'),
    (1, 'Выздоровление (стойкое улучшение)'),
    (3, 'Передача под наблюдение в другое учреждение'),
    (4, 'Выезд в другой район'),
    (5, 'Не обращался за помощью в течение года'),
    (9, 'Другие причины'),
    (10, 'Выбытие в стационарное учреждение соцобслуживания'),
    (11, 'Снятие диагноза психического заболевания'),
    (14, 'Отсутствие сведений длительное время'),
    (99, 'Стоит на учете, статус неизвестен'),
    (100, 'Первичный'),
    (101, 'Повторно')
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.direct (id, description) VALUES
    (-1, 'Не указано'),
    (99, 'Неизвестно'),
    (1, 'Самообращение')
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.direct_from (id, description) VALUES
    (-1, 'Не указано'),
    (1, 'Неизвестно')
ON CONFLICT (id) DO NOTHING;

INSERT INTO test."end" (id, description) VALUES
    (1, 'Основные документы')
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.document (id, id_end, description) VALUES
    (1, 1, 'Протокол ВК')
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.type_work_place (id, description) VALUES
    (1, 'Не указано')
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.who_closed (id, who) VALUES
    (1, 'ПТ'),
    (2, 'Участковая служба'),
    (3, 'Дневной стационар'),
    (4, 'Больница')
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.tsuicide (id, description) VALUES
    (0, 'Демонстративный'),
    (1, 'Истинный')
ON CONFLICT (id) DO NOTHING;

INSERT INTO library.analizes (id, name) VALUES
    (1, 'Туберкулез'),
    (2, 'RW')
ON CONFLICT (id) DO NOTHING;

INSERT INTO library.preparate_list (id, international_name, description, dose) VALUES
    (1, 'Не указан', 'Не указан', '')
ON CONFLICT (id) DO NOTHING;

INSERT INTO library.contact_list (id, name) VALUES
    (1, 'Не указан')
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.diagnos (id, name, code, staff_add_id) VALUES
    (1, 'Диагноз не указан', 'F00.0', 0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO test.group_diagnos (id, name, array_diagnos_id) VALUES
    (1, 'F20.0-F25.9', ARRAY[1]::bigint[]),
    (2, 'F06.0-F07.9', ARRAY[]::bigint[]),
    (3, 'F31.0-F39', ARRAY[]::bigint[]),
    (4, 'F40.0-F48', ARRAY[]::bigint[])
ON CONFLICT (id) DO NOTHING;

INSERT INTO reports_library.analize_vyt_group_diagnos (id, name, group_diagnos) VALUES
    (1, 'F20.0-F25.9', ARRAY[1]::bigint[]),
    (2, 'F06.0-F07.9', ARRAY[]::bigint[]),
    (3, 'F31.0-F39', ARRAY[]::bigint[]),
    (4, 'F40.0-F48', ARRAY[]::bigint[])
ON CONFLICT (id) DO NOTHING;

INSERT INTO messager."group" (id, name, staff_id) VALUES
    (1, 'Общая', ARRAY[1]::bigint[])
ON CONFLICT (id) DO NOTHING;

-- Keep identity generators above all explicit seed identifiers.
SELECT setval(pg_get_serial_sequence('library.departments', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM library.departments), 1), 1), true);
SELECT setval(pg_get_serial_sequence('test.area', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM test.area), 1), 1), true);
SELECT setval(pg_get_serial_sequence('test.staff', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM test.staff), 1), 1), true);
SELECT setval(pg_get_serial_sequence('test.street', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM test.street), 1), 1), true);
SELECT setval(pg_get_serial_sequence('test.users', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM test.users), 1), 1), true);
SELECT setval(pg_get_serial_sequence('test.document', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM test.document), 1), 1), true);
SELECT setval(pg_get_serial_sequence('test.type_work_place', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM test.type_work_place), 1), 1), true);
SELECT setval(pg_get_serial_sequence('library.analizes', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM library.analizes), 1), 1), true);
SELECT setval(pg_get_serial_sequence('library.preparate_list', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM library.preparate_list), 1), 1), true);
SELECT setval(pg_get_serial_sequence('library.contact_list', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM library.contact_list), 1), 1), true);
SELECT setval(pg_get_serial_sequence('test.diagnos', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM test.diagnos), 1), 1), true);
SELECT setval(pg_get_serial_sequence('test.group_diagnos', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM test.group_diagnos), 1), 1), true);
SELECT setval(pg_get_serial_sequence('messager."group"', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM messager."group"), 1), 1), true);

COMMIT;
